#!/bin/sh

cdr="$HOME/.config"
bcdr="$HOME/boiled-rice/config"
bmdr="$HOME/boiled-rice/media"

mirrors(){
	read -p "Your Country [ To refresh pacman mirrorlist ](example - India): " cnt
	sudo pacman -S reflector rsync --noconfirm
	clear && echo "Refreshing mirrorlist for $cnt"
	sudo reflector -c $cnt -a 5 --sort rate --save /etc/pacman.d/mirrorlist >/dev/null
}

install_brillo(){
	git clone https://github.com/CameronNemo/brillo.git $HOME/brillo
	cd $HOME/brillo
	make
	sudo make install.setgid
	sudo rm -rf $HOME/brillo
}

install_yay(){
	git clone https://aur.archlinux.org/yay.git $HOME/yay
	cd $HOME/yay
	makepkg -si
	sudo rm -rf $HOME/yay
}

install_base(){
	file="$HOME/harbs/static/prog.csv"
	for i in $(awk -F',' '{print $2}' "$file")
	do
    		sudo pacman -S "$i" --noconfirm
	done
}

install_wm(){	
	progi=("dwm" "st" "dmenu" "slstatus")
	for i in "${progi[@]}"
	do
		clear && echo "Installing dwm, dmenu, st and slstatus"
		cd $cdr/suckless/$i && sudo cp config.def.h config.h && sudo make install >/dev/null
	done
}

mk_dirs(){
	mkdir -p $HOME/pix/wall $HOME/pix/ss
	mkdir -p $HOME/.config $HOME/.local/share $HOME/.local/state
}

cp_files(){
	cp -r $bcdr/* $cdr/
	cp -r $bmdr/wall.png $HOME/pix/wall/wall.png
}

install_zsh(){
	sudo cp $HOME/boiled-rice/tmp/zshenv /etc/zsh/
}
