#!/bin/sh

cdr="$HOME/.config"
bcdr="$HOME/boiled-rice/config"
bmdr="$HOME/boiled-rice/media"

mirrors(){
	read -p "Your Country [ To refresh pacman mirrorlist ](example - India): " cnt
	sudo pacman -S archlinux-keyring gnome-keyring reflector rsync --noconfirm
	clear && echo "Refreshing mirrorlist for $cnt"
	sudo reflector -c $cnt -a 5 --sort rate --save /etc/pacman.d/mirrorlist >/dev/null
}

install_brillo(){
	git clone https://github.com/CameronNemo/brillo.git $HOME/brillo
	cd $HOME/brillo
	make
	sudo make install.setgid
	sudo rm -rf $HOME/brillo
}

install_yay(){
	git clone https://aur.archlinux.org/yay.git $HOME/yay
	cd $HOME/yay
	makepkg -si
	sudo rm -rf $HOME/yay
}

install_base(){
	file="$HOME/harbs/static/prog.csv" 
	for i in $(awk -F',' '{print $2}' "$file") 
	do
    		sudo pacman -S "$i" --noconfirm
	done
}

install_wm(){	
	progi=("dwm" "st" "dmenu" "slstatus")
	for i in "${progi[@]}"
	do
		clear && echo "Installing dwm, dmenu, st and slstatus"
		cd $cdr/suckless/$i && sudo cp config.def.h config.h && sudo make install >/dev/null
	done
}

mk_dirs(){
	mkdir -p $HOME/pix/wall $HOME/pix/ss $HOME/music
	mkdir -p $HOME/.config $HOME/.local/state
	mkdir $HOME/.config/git
}

cp_files(){
	cp -r $HOME/boiled-rice/local/* $HOME/.local/
	cp -r $bcdr/* $cdr/
	cp -r $bmdr/wall.png $HOME/pix/wall/wall.png
}

install_zsh(){
	sudo cp $HOME/boiled-rice/tmp/zshenv /etc/zsh/
	chsh -s /bin/zsh
}

clean_up(){
	rm .bash_history .bash_profile .bashrc .bash_logout
	clear && echo "Installation over, cleaning up ~/ . harbs folder can be deleted after this"
	rm -rf $HOME/boiled-rice $HOME/harbs
	sleep 4s
}

graphic_driver()
{
echo "Graphic Drivers: "
echo "1. AMD 		2. INTEL 		3. NVIDIA"
read -p "Enter your choice [Default 1]: " choice

case $choice in
  1)
    sudo pacman -S xf86-video-amdgpu
    ;;
  2)
    sudo pacman -S xf86-video-intel
    ;;
  3)
    sudo pacman -S nvidia nvidia-utils
    ;;
  *)
    sudo pacman -S xf86-video-amdgpu 
    ;;
esac
}

srvces(){
	systemctl enable NetworkManager
	systemctl enable bluetooth
	systemctl enable cups
	systemctl --user enable mpd
}
